version: "3"

services:
  spark:
    image: bitnami/spark:3.5.1
    container_name: spark
    networks:
      data-lake-network:
    environment:
      - SPARK_MODE=master
      - SPARK_RPC_AUTHENTICATION_ENABLED=no
      - SPARK_RPC_ENCRYPTION_ENABLED=no
      - SPARK_LOCAL_STORAGE_ENCRYPTION_ENABLED=no
      - SPARK_SSL_ENABLED=no
      - SPARK_USER=spark
    ports:
      - "4040:4040"
      - "8085:8080"
      - "7077:7077"
      - "10000:10000"

  spark-worker:
    image: bitnami/spark:3.5.1
    container_name: spark-worker
    networks:
      data-lake-network:
    environment:
      - SPARK_MODE=worker
      - SPARK_MASTER_URL=spark://spark:7077
      - SPARK_WORKER_MEMORY=1G
      - SPARK_WORKER_CORES=1
      - SPARK_RPC_AUTHENTICATION_ENABLED=no
      - SPARK_RPC_ENCRYPTION_ENABLED=no
      - SPARK_LOCAL_STORAGE_ENCRYPTION_ENABLED=no
      - SPARK_SSL_ENABLED=no
      - SPARK_USER=spark
    depends_on:
      - spark

  jupyter:
    build:
      context: .
      dockerfile: jupyter/Dockerfile
    networks:
      data-lake-network:
    ports:
      - "8888:8888"
    volumes:
      - ./jupyter/notebooks:/home/jovyan/work
    env_file:
      - .env
    command: start-notebook.sh


networks:
  data-lake-network: 
